In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3,])
a

array([1, 2, 3])

In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
print(np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [7]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

## Add, Remove, and Sort

In [8]:
arr = np.array([1,2,3,4,5,6,7,8])

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [11]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [12]:
arr = np.array([2,1,3,4,5,6,7,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

In [13]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7,]],
                          [[0, 1, 2, 3],
                          [4, 5, 6, 7,]],
                          [[0, 1, 2, 3],
                          [4, 5, 6, 7,]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [14]:
array_example.ndim

3

In [15]:
array_example.size

24

In [16]:
array_example.shape

(3, 2, 4)

In [17]:
arr_one = np.array([[1, 2, 3, 4, 5]])
arr_one.ndim

2

In [18]:
arr_one.size

5

In [19]:
arr_one.shape

(1, 5)

In [20]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [21]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [23]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [24]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [25]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [26]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [28]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [29]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and Slicing

In [30]:
data =  np.array([1,2,3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [31]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [33]:
five_up = (a >= 5)
print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [34]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [35]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [36]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [37]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [38]:
a_1 = np.array([[1, 1],
               [2, 2]])
a_2 = np.array([[3, 3],
               [4, 4]])

In [39]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [40]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [41]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                   [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [42]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [43]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic array operations

In [46]:
a = np.array([1,2,3,4])
a.sum()

10

In [47]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [48]:
b.sum(axis=0)

array([3, 3])

In [49]:
b.sum(axis=1)

array([2, 4])

In [50]:
data = np.array([1,2])
data

array([1, 2])

In [51]:
ones = np.ones(2)
ones

array([1., 1.])

In [52]:
data + ones

array([2., 3.])

In [53]:
data * data

array([1, 4])

In [54]:
data / data

array([1., 1.])

## Broadcasting

In [55]:
data * 2

array([2, 4])

In [56]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
             [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [57]:
A.sum()

4.8595784

In [58]:
A.min()

0.05093587

In [59]:
A.max()

0.82485143

In [60]:
A.mean()

0.4049648666666667

In [61]:
A.std()

0.21392120766089617

## Matrics

In [62]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.07072751, 0.18481644],
       [0.40600251, 0.77072132],
       [0.48959588, 0.72991425]])

In [63]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.8922093  0.55439356]
 [0.14565195 0.56747264]
 [0.71019033 0.56542126]]


In [64]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [65]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [66]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [67]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [68]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [69]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


## Matrix Indexing

In [70]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2, 1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [71]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [72]:
print(data.min())
print(data.max())
print(data.sum())

1
6
21


In [73]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [74]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [75]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [76]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [77]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [80]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [81]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [82]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [83]:
print(np.random.random((4,3,2)))

[[[0.42077475 0.21273084]
  [0.00801858 0.7357958 ]
  [0.11637982 0.75571052]]

 [[0.60437309 0.82840965]
  [0.18814772 0.70498106]
  [0.12855129 0.29464259]]

 [[0.54689818 0.32740805]
  [0.20375347 0.27540904]
  [0.34197786 0.34979559]]

 [[0.55826298 0.84050046]
  [0.40964745 0.50124422]
  [0.41341293 0.48392709]]]


## Flatten N-Dimensional Array

In [84]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [85]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [86]:
error = (1/n) * np.sum(np.square(observed =- prdiction))

NameError: name 'n' is not defined